arrays.values: { [number]: number }
arrays.nullable: { [number]: number }?
arrays.elements: { [number]: number? }
arrays.both: { [number]: number? }?
arrays.nested: { [number]: { [number]: string? }? }
arrays.projected: { [number]: number }
arrays.contravariant: { [number]: string }
arrays.return: nil
primitives.bytes: { [number]: number }
primitives.shorts: { [number]: number }
primitives.ints: { [number]: number }
primitives.longs: { [number]: number }
primitives.floats: { [number]: number }
primitives.doubles: { [number]: number }
primitives.booleans: { [number]: boolean }
primitives.chars: { [number]: string }
primitives.nullable: { [number]: number }?
primitives.return: nil
