plugins {
    id("java-gradle-plugin")
    id("maven-publish")
    kotlin("jvm") version "2.2.0"
    kotlin("plugin.serialization") version "1.9.0"
}

dependencies {
    implementation("io.ktor:ktor-client-core:3.1.3")
    implementation("io.ktor:ktor-client-cio:3.1.3")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.1")
    implementation("com.charleskorn.kaml:kaml:0.81.0")
    implementation("com.squareup:kotlinpoet:2.2.0")
}

repositories {
    mavenLocal()
    mavenCentral()
}

sourceSets {
    val generated by creating {
        kotlin.srcDir("src/generated/")
    }

    named("main") {
        compileClasspath += generated.output
        runtimeClasspath += generated.output
    }
}

kotlin {
    jvmToolchain(21)
    compilerOptions {
        freeCompilerArgs.add("-Xcontext-parameters")
    }
}

tasks.named("build") {
    dependsOn("generateTypes")
}

tasks.register<JavaExec>("generateTypes") {
    group = "build"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("com.rbxkt.typegen.MainKt")

    dependsOn("publishToMavenLocal")
}

tasks.jar {
    from(sourceSets["generated"].output)
}