plugins {
    id("maven-publish")
    kotlin("jvm") version "2.2.0"
    kotlin("plugin.serialization") version "1.9.0"
}

dependencies {
    implementation("io.ktor:ktor-client-core:3.1.3")
    implementation("io.ktor:ktor-client-cio:3.1.3")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.1")
    implementation("com.charleskorn.kaml:kaml:0.81.0")
    implementation("com.squareup:kotlinpoet:2.2.0")
}

repositories {
    mavenLocal()
    mavenCentral()
}

val generatedTypesDirectory = layout.buildDirectory.dir("generated/sources/roblox")

sourceSets {
    val generated by creating {
        kotlin.srcDir(generatedTypesDirectory)
    }
}

dependencies {
    "generatedImplementation"(kotlin("stdlib"))
}

kotlin {
    jvmToolchain(21)
    compilerOptions {
        freeCompilerArgs.add("-Xcontext-parameters")
    }
}

val generateTypes by tasks.registering(JavaExec::class) {
    group = "build"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("com.rbxkt.typegen.MainKt")

    args(generatedTypesDirectory.get().asFile.absolutePath)
    outputs.dir(generatedTypesDirectory)
    javaLauncher.set(javaToolchains.launcherFor { languageVersion.set(JavaLanguageVersion.of(21)) })
    dependsOn(tasks.named("classes"))
}

tasks.named("compileGeneratedKotlin") {
    dependsOn(generateTypes)
}

val generatedTypesJar by tasks.registering(Jar::class) {
    description = "Packages only the generated Roblox API classes."
    archiveBaseName.set("types")
    destinationDirectory.set(layout.buildDirectory.dir("type-publication"))
    from(sourceSets["generated"].output)
}

val generatedTypesSourcesJar by tasks.registering(Jar::class) {
    archiveBaseName.set("types")
    archiveClassifier.set("sources")
    destinationDirectory.set(layout.buildDirectory.dir("type-publication"))
    dependsOn(generateTypes)
    from(generatedTypesDirectory)
}

tasks.named("assemble") {
    dependsOn(generatedTypesJar, generatedTypesSourcesJar)
}

publishing {
    publications {
        create<MavenPublication>("robloxTypes") {
            artifactId = "types"
            artifact(generatedTypesJar)
            artifact(generatedTypesSourcesJar)
            pom {
                name.set("rbxkt Roblox Types")
                description.set("Generated Kotlin API declarations for the Roblox Luau transpiler.")
                // The generator runs at build time. Consumers only need Kotlin's
                // standard library, never Ktor, KotlinPoet, or the YAML parser.
                withXml {
                    asNode().appendNode("dependencies").appendNode("dependency").apply {
                        appendNode("groupId", "org.jetbrains.kotlin")
                        appendNode("artifactId", "kotlin-stdlib")
                        appendNode("version", "2.2.0")
                        appendNode("scope", "compile")
                    }
                }
            }
        }
    }
}

tasks.withType<AbstractPublishToMaven>().configureEach {
    dependsOn(tasks.named("check"))
}

val creatorDocsTest by tasks.registering(JavaExec::class) {
    group = "verification"
    description = "Tests creator-docs fetching and schema compatibility using local fixtures."
    dependsOn(tasks.named("testClasses"))
    classpath = sourceSets.test.get().runtimeClasspath
    mainClass.set("com.rbxkt.typegen.CreatorDocsTestKt")
    javaLauncher.set(javaToolchains.launcherFor { languageVersion.set(JavaLanguageVersion.of(21)) })
}

tasks.named("test") {
    dependsOn(creatorDocsTest)
}

tasks.register<JavaExec>("verifyLiveCreatorDocs") {
    group = "verification"
    description = "Generates types from current upstream creator docs in a temporary directory."
    dependsOn(tasks.named("testClasses"))
    classpath = sourceSets.test.get().runtimeClasspath
    mainClass.set("com.rbxkt.typegen.CreatorDocsTestKt")
    args("--live")
    javaLauncher.set(javaToolchains.launcherFor { languageVersion.set(JavaLanguageVersion.of(21)) })
}
