//Generated by codex astra medium, I can't be asked to write tests rn

package xyz.atkdev.rbxkt.luau

import org.jetbrains.kotlin.backend.common.extensions.IrGenerationExtension
import org.jetbrains.kotlin.backend.common.extensions.IrPluginContext
import org.jetbrains.kotlin.cli.common.ExitCode
import org.jetbrains.kotlin.cli.jvm.K2JVMCompiler
import org.jetbrains.kotlin.compiler.plugin.CompilerPluginRegistrar
import org.jetbrains.kotlin.config.CompilerConfiguration
import org.jetbrains.kotlin.ir.declarations.IrModuleFragment
import org.jetbrains.kotlin.ir.declarations.IrSimpleFunction
import java.io.ByteArrayOutputStream
import java.io.File
import java.io.PrintStream
import java.nio.file.Files
import java.util.jar.JarEntry
import java.util.jar.JarOutputStream

// Loaded by the compiler through a temporary service-only plugin JAR. The test
// classpath supplies this class; the production emitter is deliberately not run.
class TypeRenderingGoldenRegistrar : CompilerPluginRegistrar() {
    override val supportsK2 = true

    override fun ExtensionStorage.registerExtensions(configuration: CompilerConfiguration) {
        IrGenerationExtension.registerExtension(object : IrGenerationExtension {
            override fun generate(moduleFragment: IrModuleFragment, pluginContext: IrPluginContext) {
                val previousContext = LuauTypeSolver.irContext
                LuauTypeSolver.irContext = pluginContext
                try {
                    rendered = buildString {
                        moduleFragment.files.forEach { file ->
                            file.declarations.filterIsInstance<IrSimpleFunction>().forEach { function ->
                                function.parameters.forEach { parameter ->
                                    appendLine("${function.name}.${parameter.name}: ${LuauTypeSolver.fromIr(parameter.type)}")
                                }
                                appendLine("${function.name}.return: ${LuauTypeSolver.fromIr(function.returnType)}")
                            }
                        }
                    }
                } finally {
                    LuauTypeSolver.irContext = previousContext
                }
            }
        })
    }

    companion object {
        var rendered: String? = null
    }
}

fun main(args: Array<String>) {
    val fixtureDir = File(args.single())
    val fixtures = fixtureDir.listFiles { file -> file.extension == "kt" }
        ?.sortedBy { it.name }.orEmpty()
    check(fixtures.isNotEmpty()) { "No type-rendering fixtures in $fixtureDir" }
    val workDir = Files.createTempDirectory("rbxkt-type-goldens-").toFile()
    val failures = mutableListOf<String>()
    try {
        val pluginJar = File(workDir, "type-rendering-plugin.jar")
        JarOutputStream(pluginJar.outputStream()).use { jar ->
            jar.putNextEntry(JarEntry("META-INF/services/org.jetbrains.kotlin.compiler.plugin.CompilerPluginRegistrar"))
            jar.write(TypeRenderingGoldenRegistrar::class.java.name.toByteArray())
            jar.closeEntry()
        }
        val stdlib = File(Unit::class.java.protectionDomain.codeSource.location.toURI())
        for (fixture in fixtures) {
            val golden = File(fixtureDir, "${fixture.nameWithoutExtension}.luau")
            if (!golden.isFile) {
                failures += "${fixture.name}: missing ${golden.name}"
                continue
            }
            TypeRenderingGoldenRegistrar.rendered = null
            val diagnostics = ByteArrayOutputStream()
            val exitCode = PrintStream(diagnostics).use { messages ->
                K2JVMCompiler().exec(
                    messages,
                    "-no-stdlib", "-no-reflect", "-classpath", stdlib.absolutePath,
                    "-Xplugin=${pluginJar.absolutePath}",
                    "-d", File(workDir, fixture.nameWithoutExtension).absolutePath,
                    fixture.absolutePath,
                )
            }
            if (exitCode != ExitCode.OK) {
                failures += "${fixture.name}: compiler failed ($exitCode)\n$diagnostics"
                continue
            }
            val expected = golden.readText().replace("\r\n", "\n")
            val actual = TypeRenderingGoldenRegistrar.rendered
            if (actual != expected) {
                failures += "${fixture.name}: golden mismatch\nEXPECTED:\n$expected\nACTUAL:\n$actual"
            } else {
                println("PASS ${fixture.name}")
            }
        }
    } finally {
        workDir.deleteRecursively()
        TypeRenderingGoldenRegistrar.rendered = null
    }
    failures.forEach { System.err.println(it) }
    check(failures.isEmpty()) { "${failures.size}/${fixtures.size} type-rendering golden fixtures failed" }
    println("All ${fixtures.size} type-rendering golden fixtures passed")
}
