package xyz.atkdev.rbxkt.ir

import org.jetbrains.kotlin.ir.IrElement
import org.jetbrains.kotlin.ir.declarations.*
import org.jetbrains.kotlin.ir.overrides.isNonPrivate
import org.jetbrains.kotlin.ir.types.isUnit
import org.jetbrains.kotlin.ir.util.hasAnnotation
import org.jetbrains.kotlin.ir.visitors.IrVisitorVoid
import org.jetbrains.kotlin.name.FqName
import xyz.atkdev.rbxkt.luau.nameToService

internal data class LuauEntrypoint(val file: IrFile, val function: IrSimpleFunction) {
    fun render(moduleKind: String, relativePath: String): String {
        val modulePath = relativePath.substringBeforeLast('.').split('/')
            .joinToString("") { "[${quote(it)}]" }
        return """
            |-- Generated by rbxkt.
            |local modules = game:GetService("${nameToService(moduleKind)}").rbxkt.Modules
            |local entrypoint = require(modules["$moduleKind"]$modulePath)
            |entrypoint[${quote(function.name.asString())}]()
            |
        """.trimMargin()
    }
}

private fun quote(value: String): String = "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

internal fun findEntrypoint(files: List<IrFile>, moduleKind: String): LuauEntrypoint? {
    val entrypoints = mutableListOf<LuauEntrypoint>()
    files.forEach { file ->
        file.accept(object : IrVisitorVoid() {
            override fun visitElement(element: IrElement) {
                if (element is IrSimpleFunction && element.hasAnnotation(FqName("com.rbxkt.types.Entrypoint"))) {
                    val label = "@Entrypoint ${element.name} in ${file.path}"
                    require(moduleKind != "shared") { "$label cannot be declared in shared code" }
                    require(element.parent is IrFile && element.isNonPrivate && element.body != null &&
                        element.parameters.isEmpty() && element.typeParameters.isEmpty() &&
                        !element.isSuspend && element.returnType.isUnit()) {
                        "$label must be a non-private, top-level, non-suspend function with a body, no parameters or type parameters, and a Unit return type"
                    }
                    require(file.declarations.filterIsInstance<IrSimpleFunction>().count { it.name == element.name } == 1) {
                        "$label cannot be overloaded"
                    }
                    entrypoints += LuauEntrypoint(file, element)
                }
                element.acceptChildren(this, null)
            }
        }, null)
    }
    require(entrypoints.size <= 1) {
        "Only one @Entrypoint is allowed for $moduleKind: " +
            entrypoints.joinToString { "${it.file.path}: ${it.function.name}" }
    }
    return entrypoints.singleOrNull()
}
